### ISSUE TITLE
Can't open the game

### ISSUE THREAD

**Issue by fajarmf94** [silfumus/ElectronicObserver#50]
after visit the link game, it always white blank. why?

**Comment by silfumus** [comment]
Assuming that the DMM login page load normally,
Open `developer tools (F12)` >> `Network` tab and reload/browse to the game url. It should gives you an idea whether it is application-related or network-related problem. Just wait it out if there's a network activity, since KanColle Phase 2 assets are relatively bigger.

If you need further assistance, state your ISP and network type (e.g: cable, dsl, 4G, etc), along with screenshot of the `network` tab. I'll try recreate the problem.

The screenshot should be similar to pic related.
![network](https://user-images.githubusercontent.com/6127734/45243571-8cf41f80-b31e-11e8-9242-6e42449b8836.png)
